# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:jenkins:.
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9  # Use an image that includes Python
    steps:
      - checkout
      - run:
          name: Setup Python
          command: |
            sudo apt-get update
            sudo apt-get install -y python3

      - run:
          name: Checkout and Build
          command: |
            git clone https://github.com/ShahAman/jenkins_webhook.git
            cd jenkins_webhook
            python3 ops.py

  test:
    docker:
      - image: cimg/python:3.9  # Use an image that includes Python
    steps:
      - checkout
      - run:
          name: Setup Python
          command: |
            sudo apt-get update
            sudo apt-get install -y python3

      - run:
          name: Run Tests
          command: |
            python3 -m pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

